spring:
  application:
    name: discovery-service
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1

---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: peer1
server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: peer1.com
    metadataMap:
      zone: zone1

  client:
    serviceUrl:
      defaultZone: http://peer2.com:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: ${PORT:8762}
eureka:
  instance:
    hostname: peer2.com
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://peer1.com:8761/eureka/
