spring:
  application:
    name: delete-user-service
  zipkin:
    baseUrl: http://localhost:9411/
  h2:
    console:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true


spring.datasource.url: jdbc:postgresql://localhost:5432/SMS
spring.datasource.username: postgres
#spring.datasource.password: 123456
spring.datasource.password: 123456789
spring.main.allow-bean-definition-overriding: true
spring.jpa.hibernate.ddl-auto: update
---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: zone1
server:
  port: ${PORT:6091}
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: zone2
server:
  port: ${PORT:6092}
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE

management.endpoints.web.exposure.include: hystrix.stream