spring:
  application:
    name: authentication-service
server:
  port: ${PORT:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

spring.datasource.url: jdbc:postgresql://localhost:5432/SMS
spring.datasource.username: postgres
#spring.datasource.password: 123456789
spring.datasource.password: 123456
spring.main.allow-bean-definition-overriding: true

