## rabbitMQ
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
rabbitmq.exchange: direct

spring:
  application:
    name: send-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: zone1
server:
  port: ${PORT:5050}
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/
---
spring:
  profiles: zone2
server:
  port: ${PORT:5051}
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/
