## rabbitMQ
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
rabbitmq.exchange: direct

spring.datasource.url: jdbc:postgresql://localhost:5432/SMS
spring.datasource.username: postgres
spring.datasource.password: 123456789
spring.main.allow-bean-definition-overriding: true

spring:
  application:
    name: send-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: zone1
server:
  port: ${PORT:5050}
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: zone2
server:
  port: ${PORT:5051}
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
