spring:
  application:
    name: send-service
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
    service:
      name: send-service
    enabled: true
  sleuth:
    enabled: true
    sampler.probability: 1

spring.datasource.url: jdbc:postgresql://localhost:5432/SMS
spring.datasource.username: postgres
spring.datasource.password: 123456789
spring.main.allow-bean-definition-overriding: true


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: zone1
server:
  port: ${PORT:5050}
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: zone2
server:
  port: ${PORT:5051}
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: TRACE

management.endpoints.web.exposure.include: hystrix.stream