spring:
  application:
    name: send-and-receive-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

spring.datasource.url: jdbc:postgresql://localhost:5432/SMS
spring.datasource.username: postgres
#spring.datasource.password: 123456789
spring.datasource.password: 123456
spring.main.allow-bean-definition-overriding: true


---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: zone1
server:
  port: ${PORT:7091}
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: zone2
server:
  port: ${PORT:7092}
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
