spring:
  application:
    name: agent-service
server:
  port: ${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
endpoints:
  shutdown:
    enabled: true
    sensitive: false

spring.datasource.url: jdbc:postgresql://localhost:5432/SMS
spring.datasource.username: postgres
spring.datasource.password: 123456789
spring.main.allow-bean-definition-overriding: true
