## rabbitMQ
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest
rabbitmq.exchange: direct

spring:
  application:
    name: receive-service

spring.zipkin.baseUrl: http://localhost:9411/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: zone1
server:
  port: ${PORT:7091}
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: zone2
server:
  port: ${PORT:7092}
eureka:
  instance:
    metadataMap:
      zone: zone2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
