spring:
  application:
    name: getway-service
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1

spring.zipkin.baseUrl: http://localhost:9411/

zuul:
  prefix: /api
  routes:
    agent:
      path: /addUser/**
      serviceId: add-user-service
    authentication:
      path: /search/**
      serviceId: search-service
    message:
      path: /message/**
      serviceId: send-service
    del:
      path: /deleteUser/**
      serviceId: delete-user-service

ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: zone1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka:  false
    preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: zone1
server:
  port: ${PORT:8765}

---
spring:
  profiles: zone2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka:  false
    preferSameZoneEureka: true

  instance:
    metadataMap:
      zone: zone2
server:
  port: ${PORT:8766}

