spring:
  application:
    name: getway-service
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
    service:
      name: gateway-service
    enabled: true
  sleuth:
    enabled: true
    sampler.probability: 1



zuul:
  prefix: /api
  routes:
    agent:
      path: /addUser/**
      serviceId: add-user-service
    authentication:
      path: /search/**
      serviceId: search-service
    message:
      path: /message/**
      serviceId: send-service
    del:
      path: /deleteUser/**
      serviceId: delete-user-service
    log:
      path: /log/**
      serviceId: log-service

---
spring:
  profiles: zone1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka:  true
    preferSameZoneEureka: true
    preferIpAddress: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    metadataMap:
      zone: zone1
server:
  port: ${PORT:8765}

---
spring:
  profiles: zone2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka:  true
    preferSameZoneEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true
    metadataMap:
      zone: zone2
server:
  port: ${PORT:8766}


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  read-timeout: 60000
  connection-timeout: 3000
  max-auto-retries: 0
  max-auto-retries-next-server: 1
  eureka:
    enabled: true


