spring:
  application:
    name: getway-service
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1

zuul:
  prefix: /api
  routes:
    agent:
      path: /agent/**
      serviceId: agent-service
    authentication:
      path: /authentication/**
      serviceId: authentication-service
    message:
      path: /message/**
      serviceId: message-service

ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: zone1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka:  false
    preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: zone1
server:
  port: ${PORT:8765}

---
spring:
  profiles: zone2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    registerWithEureka:  false
    preferSameZoneEureka: true

  instance:
    metadataMap:
      zone: zone2
server:
  port: ${PORT:8766}

